### ISSUE TITLE
Продвинутый режим редактора

### ISSUE THREAD

**Issue by BorodinDK** [Tour-360/tour-player#312]
1. при редактировании перемещаться при помощи галлереи, поворачивать все панорамы на север, а по завершению нажимать сочетание клавиш и копировать весь json целиком
2. таким же образом проставлять маркеры
3. хранить Новый json в localstorage (защита от случайных обновлений)
4. При заходе в режим редактора сверху появляеться панель с кнопками
5. Возможность создать все связи не открывая редактор

Открыто для обсуждений

**Comment by Borodin** [comment]
Встроить продвинутый редактор в обычную сборку?

**Comment by BorodinDK** [comment]
> Встроить продвинутый редактор в обычную сборку?

да
