### ISSUE TITLE
Исправить ошибки в UI.Marker

### ISSUE THREAD

**Issue by Borodin** [Tour-360/tour-player#49]
- [x] [Перенести проверку в внутрь функции](https://github.com/Tour-360/tour-player/blob/dev/src/js/UI/Marker.js#L22-L27)
 - [x] Сделать чтоб классы у тайтлов не мигали
 - [x] Сделать курсор ```pointer``` на маркеры
 - [x] Исправить не кликабельность маркеров (```padding``` от title)
 - [x] Добавить метод удаления маркера
 - [x] Поправить отображение тайтла в нижнем положении

![image](https://cloud.githubusercontent.com/assets/645491/12246961/911dbe26-b8c2-11e5-91ca-f8b239e26564.png)

**Comment by BorodinDK** [comment]
Что с кликабельностью маркеров не так?

**Comment by Borodin** [comment]
они не прокликиваются
