### ISSUE TITLE
Определить внешний вид ссылок

### ISSUE THREAD

**Issue by Borodin** [Tour-360/tour-player#58]
```stylus
$linkColor = #0080ff
$activeLinkColor = #ff3600
```
![image](https://cloud.githubusercontent.com/assets/645491/12277661/9a209356-b98d-11e5-8583-5c948bf082c8.png)

**Comment by BorodinDK** [comment]
![2016-01-13 11 22 44](https://cloud.githubusercontent.com/assets/4511390/12289725/1602c632-b9ee-11e5-836d-f37b4fb5f158.png)
